// build_source.mjs - Generates tts.s for gemini-38flash-v1
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PHONEMES, PHONEME_LIST, EXCEPTIONS } from "./generate.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));

function calcPeriod(freq) {
  if (!freq || freq <= 0) return 0;
  return Math.round(98339.84 / freq);
}

function generateSource() {
  const lines = [];
  const emit = line => lines.push(line);

  emit("; ==========================================================================");
  emit("; 3RIC TALKS V1 - ORIGINAL ENGLISH TEXT-TO-SPEECH ENGINE");
  emit("; Submission ID: gemini-38flash-v1");
  emit("; Author: Gemini 3.8 Flash (via GitHub Copilot)");
  emit("; Target: 3RIC 65C02 Computer with Slot-4 Dual-AY-3-8910 Mockingboard");
  emit("; ==========================================================================");
  emit("");
  emit("        .org $0800");
  emit("");
  emit("; Entry point for BRUN / web runner");
  emit("START:");
  emit("        jmp UI");
  emit("");
  emit("; --------------------------------------------------------------------------");
  emit("; HARDWARE & ROM EQUATES");
  emit("; --------------------------------------------------------------------------");
  emit("KBD             = $C000     ; Keyboard data (bit 7 = key pressed strobe)");
  emit("KBD_STROBE      = $C010     ; Clear keyboard strobe");
  emit("TEXT_SW         = $C051     ; Select text mode");
  emit("FULL_SW         = $C052     ; Select full screen (clear mixed)");
  emit("PAGE1_SW        = $C054     ; Select display page 1");
  emit("");
  emit("MB_LEFT         = $C400     ; Slot 4 Left VIA / AY-3-8910 base");
  emit("MB_RIGHT        = $C480     ; Slot 4 Right VIA / AY-3-8910 base");
  emit("VIA_ORB         = 0         ; VIA Port B (control lines: BC1, BDIR, /RESET)");
  emit("VIA_ORA         = 1         ; VIA Port A (AY data bus)");
  emit("VIA_DDRB        = 2         ; VIA Port B Data Direction");
  emit("VIA_DDRA        = 3         ; VIA Port A Data Direction");
  emit("");
  emit("ROM_HOME        = $FC58     ; Clear text screen and home cursor");
  emit("ROM_COUT        = $FDED     ; Print character in A (high bit set) to screen & serial");
  emit("ROM_CROUT       = $FD8E     ; Print carriage return");
  emit("ROM_RDKEY       = $FD0C     ; Read key from keyboard (returns with high bit set)");
  emit("ROM_BELL        = $FF3A     ; Emit alert bell");
  emit("");
  emit("; --------------------------------------------------------------------------");
  emit("; ZERO-PAGE APPLICATION VARIABLES ($E0..$EF)");
  emit("; --------------------------------------------------------------------------");
  emit("ZP_PTR_IN_L     = $E0");
  emit("ZP_PTR_IN_H     = $E1");
  emit("ZP_PTR_DICT_L   = $E2");
  emit("ZP_PTR_DICT_H   = $E3");
  emit("ZP_WORD_LEN     = $E4");
  emit("ZP_WORD_IDX     = $E5");
  emit("ZP_PHON_COUNT   = $E6");
  emit("ZP_CUR_PHON     = $E7");
  emit("ZP_FRAME_CNT    = $E8");
  emit("ZP_AY_VAL       = $E9");
  emit("ZP_AY_BASE      = $EA");
  emit("ZP_F1_L         = $EB");
  emit("ZP_F1_H         = $EC");
  emit("ZP_F2_L         = $ED");
  emit("ZP_F2_H         = $EE");
  emit("ZP_ESCAPE_HIT   = $EF");
  emit("");
  emit("; --------------------------------------------------------------------------");
  emit("; PHONEME ID CONSTANTS");
  emit("; --------------------------------------------------------------------------");
  for (const p of PHONEME_LIST) {
    emit(`P_${p.name.padEnd(14)} = ${p.id}`);
  }
  emit("");
  emit("; ==========================================================================");
  emit("; CALLABLE INTERFACE: TTS_INIT");
  emit("; Initializes the Mockingboard dual-AY sound hardware and mutes all channels.");
  emit("; Safe to call immediately after PRG load.");
  emit("; ==========================================================================");
  emit("TTS_INIT:");
  emit("        php");
  emit("        sei");
  emit("        cld");
  emit("        ldx #0");
  emit("        jsr AY_INIT_CHIP");
  emit("        ldx #$80");
  emit("        jsr AY_INIT_CHIP");
  emit("        jsr AY_MUTE_ALL");
  emit("        plp");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; CALLABLE INTERFACE: TTS_SPEAK");
  emit("; Speaks NUL-terminated ASCII text in RAM.");
  emit("; Entry: A = low pointer, X = high pointer");
  emit("; Exit:  A = 0 (complete/empty), 1 (cancelled), 2 (invalid/overlength)");
  emit("; Input string is completely preserved.");
  emit("; Upper ROM and caller state preserved.");
  emit("; ==========================================================================");
  emit("TTS_SPEAK:");
  emit("        sta ZP_PTR_IN_L");
  emit("        stx ZP_PTR_IN_H");
  emit("        stz ZP_ESCAPE_HIT");
  emit("");
  emit("        ; Scan up to 121 characters (offsets 0..120) for NUL terminator.");
  emit("        ; If NUL found within 0..120, string length <= 120 (valid).");
  emit("        ; If offset 120 is checked and still non-NUL (Y reaches 121), return 2 (overlength).");
  emit("        ldy #0");
  emit("SCAN_LEN_LOOP:");
  emit("        lda (ZP_PTR_IN_L),y");
  emit("        beq SPEAK_LEN_OK");
  emit("        iny");
  emit("        cpy #121");
  emit("        bcc SCAN_LEN_LOOP");
  emit("        lda #2              ; Return code 2: invalid overlength");
  emit("        rts");
  emit("");
  emit("SPEAK_LEN_OK:");
  emit("        ; Check if string is empty or contains only whitespace");
  emit("        ldy #0");
  emit("CHECK_EMPTY_LOOP:");
  emit("        lda (ZP_PTR_IN_L),y");
  emit("        beq INPUT_IS_EMPTY   ; Reached NUL without any non-space -> empty");
  emit("        cmp #32");
  emit("        bne INPUT_NOT_EMPTY  ; Found non-space character -> proceed to speak");
  emit("        iny");
  emit("        bra CHECK_EMPTY_LOOP");
  emit("INPUT_IS_EMPTY:");
  emit("        lda #0              ; Return code 0: completed cleanly without speech");
  emit("        rts");
  emit("");
  emit("INPUT_NOT_EMPTY:");
  emit("        ; Convert text to phonemes in PHONEME_BUF");
  emit("        jsr PARSE_TEXT_TO_PHONEMES");
  emit("        lda ZP_PHON_COUNT");
  emit("        bne DO_SYNTHESIS");
  emit("        lda #0");
  emit("        rts");
  emit("");
  emit("DO_SYNTHESIS:");
  emit("        ; Initialize sound chips");
  emit("        jsr TTS_INIT");
  emit("");
  emit("        ; Play phoneme stream");
  emit("        jsr PLAY_PHONEME_STREAM");
  emit("");
  emit("        ; Silence all channels");
  emit("        jsr AY_MUTE_ALL");
  emit("");
  emit("        ; Check cancellation return code");
  emit("        lda ZP_ESCAPE_HIT");
  emit("        beq SPEAK_SUCCESS");
  emit("        lda #1              ; Return code 1: cancelled by Escape");
  emit("        rts");
  emit("SPEAK_SUCCESS:");
  emit("        lda #0              ; Return code 0: completed successfully");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; TEXT TO PHONEME PARSER");
  emit("; Scans input string, tokenizes words, applies dictionary & rules.");
  emit("; Produces sequence of phoneme byte IDs in PHONEME_BUF.");
  emit("; ==========================================================================");
  emit("PARSE_TEXT_TO_PHONEMES:");
  emit("        stz ZP_PHON_COUNT");
  emit("        ldy #0              ; Index into input string");
  emit("");
  emit("PARSE_MAIN_LOOP:");
  emit("        lda (ZP_PTR_IN_L),y");
  emit("        bne NOT_END_OF_STRING");
  emit("        jmp PARSE_FINISH");
  emit("");
  emit("NOT_END_OF_STRING:");
  emit("        ; Check if letter (A-Z or a-z)");
  emit("        jsr IS_ALPHA");
  emit("        bcc NOT_ALPHA_CHAR");
  emit("");
  emit("        ; Accumulate word into WORD_BUF");
  emit("        ldx #0");
  emit("COLLECT_WORD_LOOP:");
  emit("        jsr TO_UPPER");
  emit("        sta WORD_BUF,x");
  emit("        inx");
  emit("        cpx #30             ; Limit word length to 30 chars");
  emit("        bcs WORD_COLLECTED");
  emit("        iny");
  emit("        lda (ZP_PTR_IN_L),y");
  emit("        beq WORD_COLLECTED");
  emit("        jsr IS_ALPHA");
  emit("        bcs COLLECT_WORD_LOOP");
  emit("");
  emit("WORD_COLLECTED:");
  emit("        stx ZP_WORD_LEN");
  emit("        phy                 ; Save input string index");
  emit("        jsr CONVERT_WORD");
  emit("        ply                 ; Restore input string index");
  emit("");
  emit("        ; Emit word pause");
  emit("        lda #P_PAUSE_WORD");
  emit("        jsr EMIT_PHONEME");
  emit("");
  emit("        ; Continue parsing");
  emit("        jmp PARSE_MAIN_LOOP");
  emit("");
  emit("NOT_ALPHA_CHAR:");
  emit("        ; Check punctuation");
  emit("        cmp #'.'");
  emit("        beq IS_SENTENCE_PUNCT");
  emit("        cmp #'?'");
  emit("        beq IS_SENTENCE_PUNCT");
  emit("        cmp #'!'");
  emit("        beq IS_SENTENCE_PUNCT");
  emit("        cmp #','");
  emit("        beq IS_CLAUSE_PUNCT");
  emit("        cmp #';'");
  emit("        beq IS_CLAUSE_PUNCT");
  emit("        cmp #':'");
  emit("        beq IS_CLAUSE_PUNCT");
  emit("        jmp NEXT_INPUT_CHAR");
  emit("");
  emit("IS_SENTENCE_PUNCT:");
  emit("        lda #P_PAUSE_SENTENCE");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp NEXT_INPUT_CHAR");
  emit("");
  emit("IS_CLAUSE_PUNCT:");
  emit("        lda #P_PAUSE_CLAUSE");
  emit("        jsr EMIT_PHONEME");
  emit("");
  emit("NEXT_INPUT_CHAR:");
  emit("        iny");
  emit("        jmp PARSE_MAIN_LOOP");
  emit("");
  emit("PARSE_FINISH:");
  emit("        ; Add final sentence pause");
  emit("        lda #P_PAUSE_SENTENCE");
  emit("        jsr EMIT_PHONEME");
  emit("        rts");
  emit("");
  emit("; Helper: Is char in A alphabetic? Sets C=1 if yes, C=0 if no.");
  emit("IS_ALPHA:");
  emit("        cmp #'A'");
  emit("        bcc IS_ALPHA_LOWER");
  emit("        cmp #'Z'+1");
  emit("        bcc IS_ALPHA_YES");
  emit("IS_ALPHA_LOWER:");
  emit("        cmp #'a'");
  emit("        bcc IS_ALPHA_NO");
  emit("        cmp #'z'+1");
  emit("        bcc IS_ALPHA_YES");
  emit("IS_ALPHA_NO:");
  emit("        clc");
  emit("        rts");
  emit("IS_ALPHA_YES:");
  emit("        sec");
  emit("        rts");
  emit("");
  emit("; Helper: Convert char in A to uppercase ASCII");
  emit("TO_UPPER:");
  emit("        cmp #'a'");
  emit("        bcc TO_UPPER_DONE");
  emit("        cmp #'z'+1");
  emit("        bcs TO_UPPER_DONE");
  emit("        sec");
  emit("        sbc #$20");
  emit("TO_UPPER_DONE:");
  emit("        rts");
  emit("");
  emit("; Helper: Append phoneme in A to PHONEME_BUF");
  emit("; Preserves A, X, Y");
  emit("EMIT_PHONEME:");
  emit("        phx");
  emit("        ldx ZP_PHON_COUNT");
  emit("        cpx #250");
  emit("        bcs EMIT_FULL");
  emit("        sta PHONEME_BUF,x");
  emit("        inc ZP_PHON_COUNT");
  emit("EMIT_FULL:");
  emit("        plx");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; WORD TRANSLATOR: CONVERT_WORD");
  emit("; Looks up WORD_BUF in exception dictionary. If not found, uses G2P rules.");
  emit("; ==========================================================================");
  emit("CONVERT_WORD:");
  emit("        ; Try dictionary lookup first");
  emit("        lda #<DICTIONARY_DATA");
  emit("        sta ZP_PTR_DICT_L");
  emit("        lda #>DICTIONARY_DATA");
  emit("        sta ZP_PTR_DICT_H");
  emit("");
  emit("DICT_SEARCH_LOOP:");
  emit("        ldy #0");
  emit("        lda (ZP_PTR_DICT_L),y   ; Length of dictionary word");
  emit("        beq DICT_NOT_FOUND      ; 0 marks end of dictionary table");
  emit("        cmp ZP_WORD_LEN");
  emit("        bne DICT_SKIP_ENTRY");
  emit("");
  emit("        ; Length matches, compare word characters");
  emit("        ldx #0");
  emit("DICT_CMP_CHARS:");
  emit("        iny");
  emit("        lda (ZP_PTR_DICT_L),y");
  emit("        cmp WORD_BUF,x");
  emit("        bne DICT_MISMATCH");
  emit("        inx");
  emit("        cpx ZP_WORD_LEN");
  emit("        bne DICT_CMP_CHARS");
  emit("");
  emit("        ; Match found! Read phoneme count and copy phonemes");
  emit("        iny");
  emit("        lda (ZP_PTR_DICT_L),y   ; Phoneme count");
  emit("        tax                     ; Count in X");
  emit("DICT_COPY_PHONEMES:");
  emit("        iny");
  emit("        lda (ZP_PTR_DICT_L),y");
  emit("        jsr EMIT_PHONEME");
  emit("        dex");
  emit("        bne DICT_COPY_PHONEMES");
  emit("        rts");
  emit("");
  emit("DICT_MISMATCH:");
  emit("        ; Re-read word length in entry to compute skip offset");
  emit("        ldy #0");
  emit("        lda (ZP_PTR_DICT_L),y");
  emit("DICT_SKIP_ENTRY:");
  emit("        ; Advance pointer past: length byte (1) + word bytes (len) + phoneme count (1) + phonemes");
  emit("        sta ZP_AY_VAL           ; save word length");
  emit("        tay");
  emit("        iny                     ; index of phoneme count byte");
  emit("        lda (ZP_PTR_DICT_L),y   ; phoneme count");
  emit("        clc");
  emit("        adc ZP_AY_VAL           ; total payload bytes");
  emit("        adc #2                  ; plus length byte and count byte");
  emit("        adc ZP_PTR_DICT_L");
  emit("        sta ZP_PTR_DICT_L");
  emit("        lda ZP_PTR_DICT_H");
  emit("        adc #0");
  emit("        sta ZP_PTR_DICT_H");
  emit("        jmp DICT_SEARCH_LOOP");
  emit("");
  emit("DICT_NOT_FOUND:");
  emit("        ; Fall back to general English G2P rules");
  emit("        jsr RULE_BASED_G2P");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; RULE-BASED ENGLISH GRAPHEME-TO-PHONEME ENGINE");
  emit("; Translates any arbitrary word in WORD_BUF using English phonetic rules.");
  emit("; ==========================================================================");
  emit("RULE_BASED_G2P:");
  emit("        stz ZP_WORD_IDX");
  emit("");
  emit("G2P_LOOP:");
  emit("        lda ZP_WORD_IDX");
  emit("        cmp ZP_WORD_LEN");
  emit("        bcc G2P_NOT_DONE");
  emit("        jmp G2P_DONE");
  emit("G2P_NOT_DONE:");
  emit("");
  emit("        ; Compute remaining characters: A = ZP_WORD_LEN - ZP_WORD_IDX");
  emit("        lda ZP_WORD_LEN");
  emit("        sec");
  emit("        sbc ZP_WORD_IDX");
  emit("        sta ZP_AY_VAL           ; remaining chars");
  emit("");
  emit("        ldx ZP_WORD_IDX");
  emit("        lda WORD_BUF,x          ; current character C");
  emit("");
  emit("        ; --- Multi-letter checks ---");
  emit("        cmp #'T'");
  emit("        bne NOT_T_PREFIX");
  emit("        ; Check TH");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_TH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'H'");
  emit("        bne NOT_TH");
  emit("        ; TH found: voiced at start of word (DH), unvoiced otherwise (TH)");
  emit("        cpx #0");
  emit("        bne TH_UNVOICED");
  emit("        lda #P_DH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("TH_UNVOICED:");
  emit("        lda #P_TH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_TH:");
  emit("        lda WORD_BUF,x");
  emit("NOT_T_PREFIX:");
  emit("");
  emit("        ; Check SH");
  emit("        cmp #'S'");
  emit("        bne NOT_S_PREFIX");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_SH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'H'");
  emit("        bne NOT_SH");
  emit("        lda #P_SH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_SH:");
  emit("        lda WORD_BUF,x");
  emit("NOT_S_PREFIX:");
  emit("");
  emit("        ; Check CH");
  emit("        cmp #'C'");
  emit("        bne NOT_C_PREFIX");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_CH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'H'");
  emit("        bne NOT_CH");
  emit("        lda #P_CH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_CH:");
  emit("        lda WORD_BUF,x");
  emit("NOT_C_PREFIX:");
  emit("");
  emit("        ; Check PH");
  emit("        cmp #'P'");
  emit("        bne NOT_P_PREFIX");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_PH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'H'");
  emit("        bne NOT_PH");
  emit("        lda #P_F");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_PH:");
  emit("        lda WORD_BUF,x");
  emit("NOT_P_PREFIX:");
  emit("");
  emit("        ; Check QU");
  emit("        cmp #'Q'");
  emit("        bne NOT_QU");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_QU");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'U'");
  emit("        bne NOT_QU");
  emit("        lda #P_K");
  emit("        jsr EMIT_PHONEME");
  emit("        lda #P_W");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_QU:");
  emit("");
  emit("        ; Check WH");
  emit("        cmp #'W'");
  emit("        bne NOT_WH");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_WH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'H'");
  emit("        bne NOT_WH");
  emit("        lda #P_W");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_WH:");
  emit("");
  emit("        ; Check CK");
  emit("        cmp #'C'");
  emit("        bne NOT_CK");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_CK");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'K'");
  emit("        bne NOT_CK");
  emit("        lda #P_K");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_CK:");
  emit("");
  emit("        ; Check NG");
  emit("        cmp #'N'");
  emit("        bne NOT_NG");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_NG");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'G'");
  emit("        bne NOT_NG");
  emit("        lda #P_NG");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_NG:");
  emit("");
  emit("        ; --- Vowel Digraphs ---");
  emit("        lda WORD_BUF,x");
  emit("        cmp #'E'");
  emit("        bne NOT_E_DIGRAPH");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_E_DIGRAPH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'E'");
  emit("        beq IS_EE_OR_EA");
  emit("        cmp #'A'");
  emit("        bne NOT_EE_OR_EA");
  emit("IS_EE_OR_EA:");
  emit("        lda #P_IY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_EE_OR_EA:");
  emit("        cmp #'R'");
  emit("        bne NOT_ER_VOWEL");
  emit("        lda #P_ER");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_ER_VOWEL:");
  emit("        lda WORD_BUF,x");
  emit("NOT_E_DIGRAPH:");
  emit("");
  emit("        cmp #'O'");
  emit("        bne NOT_O_DIGRAPH");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_O_DIGRAPH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'O'");
  emit("        bne NOT_OO");
  emit("        lda #P_UW");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_OO:");
  emit("        cmp #'A'");
  emit("        bne NOT_OA");
  emit("        lda #P_OW");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_OA:");
  emit("        cmp #'U'");
  emit("        beq IS_OU_OR_OW");
  emit("        cmp #'W'");
  emit("        bne NOT_OU_OR_OW");
  emit("IS_OU_OR_OW:");
  emit("        lda #P_AW");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_OU_OR_OW:");
  emit("        cmp #'I'");
  emit("        beq IS_OI_OR_OY");
  emit("        cmp #'Y'");
  emit("        bne NOT_OI_OR_OY");
  emit("IS_OI_OR_OY:");
  emit("        lda #P_OY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_OI_OR_OY:");
  emit("        cmp #'R'");
  emit("        bne NOT_OR_VOWEL");
  emit("        lda #P_AO");
  emit("        jsr EMIT_PHONEME");
  emit("        lda #P_R");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_OR_VOWEL:");
  emit("        lda WORD_BUF,x");
  emit("NOT_O_DIGRAPH:");
  emit("");
  emit("        cmp #'A'");
  emit("        bne NOT_A_DIGRAPH");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc NOT_A_DIGRAPH");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'I'");
  emit("        beq IS_AI_OR_AY");
  emit("        cmp #'Y'");
  emit("        bne NOT_AI_OR_AY");
  emit("IS_AI_OR_AY:");
  emit("        lda #P_EY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_AI_OR_AY:");
  emit("        cmp #'R'");
  emit("        bne NOT_AR_VOWEL");
  emit("        lda #P_AA");
  emit("        jsr EMIT_PHONEME");
  emit("        lda #P_R");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_2");
  emit("NOT_AR_VOWEL:");
  emit("        lda WORD_BUF,x");
  emit("NOT_A_DIGRAPH:");
  emit("");
  emit("        ; --- Silent E pattern check ---");
  emit("        ; If word has at least 3 letters, ends in E, and current char is vowel at (WORD_LEN - 3)");
  emit("        lda ZP_WORD_LEN");
  emit("        cmp #3");
  emit("        bcc NOT_SILENT_E");
  emit("        tax");
  emit("        lda WORD_BUF-1,x         ; Last letter of word");
  emit("        cmp #'E'");
  emit("        bne NOT_SILENT_E");
  emit("        ; Word ends in E. Is current index (WORD_LEN - 3)?");
  emit("        dex");
  emit("        dex");
  emit("        cpx ZP_WORD_IDX");
  emit("        bne CHECK_FINAL_E");
  emit("        ; Long vowel due to silent E!");
  emit("        ldx ZP_WORD_IDX");
  emit("        lda WORD_BUF,x");
  emit("        cmp #'A'");
  emit("        bne NOT_LONG_A");
  emit("        lda #P_EY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_1");
  emit("NOT_LONG_A:");
  emit("        cmp #'I'");
  emit("        bne NOT_LONG_I");
  emit("        lda #P_AY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_1");
  emit("NOT_LONG_I:");
  emit("        cmp #'O'");
  emit("        bne NOT_LONG_O");
  emit("        lda #P_OW");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_1");
  emit("NOT_LONG_O:");
  emit("        cmp #'U'");
  emit("        bne NOT_LONG_U");
  emit("        lda #P_UW");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_1");
  emit("NOT_LONG_U:");
  emit("        cmp #'Y'");
  emit("        bne NOT_SILENT_E");
  emit("        lda #P_AY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_1");
  emit("");
  emit("CHECK_FINAL_E:");
  emit("        ; If we are at the final 'E', skip it (silent E)");
  emit("        ldx ZP_WORD_LEN");
  emit("        dex");
  emit("        cpx ZP_WORD_IDX");
  emit("        bne NOT_SILENT_E");
  emit("        jmp ADVANCE_1       ; Skip final silent E");
  emit("");
  emit("NOT_SILENT_E:");
  emit("        ; --- Single Character Phoneme Translation ---");
  emit("        ldx ZP_WORD_IDX");
  emit("        lda WORD_BUF,x");
  emit("");
  emit("        ; Vowels");
  emit("        cmp #'A'");
  emit("        bne C_NOT_A");
  emit("        lda #P_AE");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_A:");
  emit("        cmp #'E'");
  emit("        bne C_NOT_E");
  emit("        ; E at end of word is usually silent; otherwise EH");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #1");
  emit("        bne E_NORMAL");
  emit("        lda ZP_WORD_LEN");
  emit("        cmp #2");
  emit("        bcs SKIP_FINAL_E");
  emit("E_NORMAL:");
  emit("        lda #P_EH");
  emit("        jsr EMIT_PHONEME");
  emit("SKIP_FINAL_E:");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_E:");
  emit("        cmp #'I'");
  emit("        bne C_NOT_I");
  emit("        lda #P_IH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_I:");
  emit("        cmp #'O'");
  emit("        bne C_NOT_O");
  emit("        lda #P_AA");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_O:");
  emit("        cmp #'U'");
  emit("        bne C_NOT_U");
  emit("        lda #P_AH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_U:");
  emit("        cmp #'Y'");
  emit("        bne C_NOT_Y");
  emit("        cpx #0");
  emit("        bne Y_NOT_START");
  emit("        lda #P_Y");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("Y_NOT_START:");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #1");
  emit("        bne Y_MIDDLE");
  emit("        lda #P_IY");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("Y_MIDDLE:");
  emit("        lda #P_IH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_Y:");
  emit("");
  emit("        ; Consonants");
  emit("        cmp #'B'");
  emit("        bne C_NOT_B");
  emit("        lda #P_B");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_B:");
  emit("        cmp #'C'");
  emit("        bne C_NOT_C");
  emit("        ; Soft C before E, I, Y");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc C_HARD");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'E'");
  emit("        beq C_SOFT");
  emit("        cmp #'I'");
  emit("        beq C_SOFT");
  emit("        cmp #'Y'");
  emit("        bne C_HARD");
  emit("C_SOFT:");
  emit("        lda #P_S");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_HARD:");
  emit("        lda #P_K");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_C:");
  emit("        cmp #'D'");
  emit("        bne C_NOT_D");
  emit("        lda #P_D");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_D:");
  emit("        cmp #'F'");
  emit("        bne C_NOT_F");
  emit("        lda #P_F");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_F:");
  emit("        cmp #'G'");
  emit("        bne C_NOT_G");
  emit("        ; Soft G before E, I, Y");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc G_HARD");
  emit("        lda WORD_BUF+1,x");
  emit("        cmp #'E'");
  emit("        beq G_SOFT");
  emit("        cmp #'I'");
  emit("        beq G_SOFT");
  emit("        cmp #'Y'");
  emit("        bne G_HARD");
  emit("G_SOFT:");
  emit("        lda #P_JH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("G_HARD:");
  emit("        lda #P_G");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_G:");
  emit("        cmp #'H'");
  emit("        bne C_NOT_H");
  emit("        lda #P_HH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_H:");
  emit("        cmp #'J'");
  emit("        bne C_NOT_J");
  emit("        lda #P_JH");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_J:");
  emit("        cmp #'K'");
  emit("        bne C_NOT_K");
  emit("        lda #P_K");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_K:");
  emit("        cmp #'L'");
  emit("        bne C_NOT_L");
  emit("        lda #P_L");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_L:");
  emit("        cmp #'M'");
  emit("        bne C_NOT_M");
  emit("        lda #P_M");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_M:");
  emit("        cmp #'N'");
  emit("        bne C_NOT_N");
  emit("        lda #P_N");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_N:");
  emit("        cmp #'P'");
  emit("        bne C_NOT_P");
  emit("        lda #P_P");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_P:");
  emit("        cmp #'R'");
  emit("        bne C_NOT_R");
  emit("        lda #P_R");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_R:");
  emit("        cmp #'S'");
  emit("        bne C_NOT_S");
  emit("        lda #P_S");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_S:");
  emit("        cmp #'T'");
  emit("        bne C_NOT_T");
  emit("        lda #P_T");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_T:");
  emit("        cmp #'V'");
  emit("        bne C_NOT_V");
  emit("        lda #P_V");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_V:");
  emit("        cmp #'W'");
  emit("        bne C_NOT_W");
  emit("        lda #P_W");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_W:");
  emit("        cmp #'X'");
  emit("        bne C_NOT_X");
  emit("        lda #P_K");
  emit("        jsr EMIT_PHONEME");
  emit("        lda #P_S");
  emit("        jsr EMIT_PHONEME");
  emit("        jmp ADVANCE_CONS_CHECK");
  emit("C_NOT_X:");
  emit("        cmp #'Z'");
  emit("        bne ADVANCE_CONS_CHECK");
  emit("        lda #P_Z");
  emit("        jsr EMIT_PHONEME");
  emit("");
  emit("ADVANCE_CONS_CHECK:");
  emit("        ; If consonant is doubled (e.g. LL, SS, TT, PP), skip the duplicate");
  emit("        ldx ZP_WORD_IDX");
  emit("        lda ZP_AY_VAL");
  emit("        cmp #2");
  emit("        bcc ADVANCE_1");
  emit("        lda WORD_BUF,x");
  emit("        cmp WORD_BUF+1,x");
  emit("        bne ADVANCE_1");
  emit("        ; Duplicate found: advance 2");
  emit("        inc ZP_WORD_IDX");
  emit("        inc ZP_WORD_IDX");
  emit("        jmp G2P_LOOP");
  emit("");
  emit("ADVANCE_2:");
  emit("        inc ZP_WORD_IDX");
  emit("ADVANCE_1:");
  emit("        inc ZP_WORD_IDX");
  emit("        jmp G2P_LOOP");
  emit("");
  emit("G2P_DONE:");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; ACOUSTIC SYNTHESIS PLAYBACK ENGINE");
  emit("; Iterates through PHONEME_BUF, programs AY-3-8910 chips, and times frames.");
  emit("; ==========================================================================");
  emit("PLAY_PHONEME_STREAM:");
  emit("        stz ZP_CUR_PHON");
  emit("");
  emit("STREAM_LOOP:");
  emit("        lda ZP_CUR_PHON");
  emit("        cmp ZP_PHON_COUNT");
  emit("        bcc STREAM_NOT_DONE");
  emit("        jmp STREAM_DONE");
  emit("STREAM_NOT_DONE:");
  emit("");
  emit("        ldx ZP_CUR_PHON");
  emit("        lda PHONEME_BUF,x");
  emit("        tax                     ; Phoneme ID in X");
  emit("");
  emit("        ; Load phoneme duration");
  emit("        lda PHON_DUR,x");
  emit("        sta ZP_FRAME_CNT");
  emit("");
  emit("        ; Check mode");
  emit("        lda PHON_MODE,x");
  emit("        bne NOT_SILENT_PAUSE");
  emit("");
  emit("        ; Silent pause: mute AY and delay");
  emit("        jsr AY_MUTE_ALL");
  emit("PAUSE_FRAME_LOOP:");
  emit("        jsr DELAY_FRAME");
  emit("        lda ZP_ESCAPE_HIT");
  emit("        bne STREAM_ABORT");
  emit("        dec ZP_FRAME_CNT");
  emit("        bne PAUSE_FRAME_LOOP");
  emit("        jmp ADVANCE_STREAM");
  emit("");
  emit("STREAM_ABORT:");
  emit("        jmp STREAM_DONE");
  emit("");
  emit("NOT_SILENT_PAUSE:");
  emit("        ; Check bit 5: plosive pre-closure silence");
  emit("        lda PHON_MODE,x");
  emit("        and #$20");
  emit("        beq NO_PRE_CLOSURE");
  emit("        ; Mute for 2 frames (~30 ms)");
  emit("        jsr AY_MUTE_ALL");
  emit("        jsr DELAY_FRAME");
  emit("        lda ZP_ESCAPE_HIT");
  emit("        bne STREAM_ABORT");
  emit("        jsr DELAY_FRAME");
  emit("        lda ZP_ESCAPE_HIT");
  emit("        bne STREAM_ABORT");
  emit("NO_PRE_CLOSURE:");
  emit("");
  emit("        ; Program AY registers for this phoneme");
  emit("        ldx ZP_CUR_PHON");
  emit("        lda PHONEME_BUF,x");
  emit("        tax");
  emit("        jsr PROGRAM_PHONEME_AY");
  emit("");
  emit("        ; Frame loop for duration of phoneme");
  emit("PHON_FRAME_LOOP:");
  emit("        ; Check bit 4: diphthong glide");
  emit("        ldx ZP_CUR_PHON");
  emit("        lda PHONEME_BUF,x");
  emit("        tax");
  emit("        lda PHON_MODE,x");
  emit("        and #$10");
  emit("        beq NO_GLIDE");
  emit("        ; Diphthong glide: in second half of duration, update to target 2");
  emit("        lda ZP_FRAME_CNT");
  emit("        cmp #5");
  emit("        bne NO_GLIDE");
  emit("        jsr PROGRAM_GLIDE_TARGET");
  emit("NO_GLIDE:");
  emit("");
  emit("        jsr DELAY_FRAME");
  emit("        lda ZP_ESCAPE_HIT");
  emit("        bne STREAM_ABORT");
  emit("        dec ZP_FRAME_CNT");
  emit("        bne PHON_FRAME_LOOP");
  emit("");
  emit("ADVANCE_STREAM:");
  emit("        inc ZP_CUR_PHON");
  emit("        jmp STREAM_LOOP");
  emit("");
  emit("STREAM_DONE:");
  emit("        jsr AY_MUTE_ALL");
  emit("        rts");
  emit("");
  emit("; Program AY registers for phoneme X");
  emit("PROGRAM_PHONEME_AY:");
  emit("        lda PHON_F1_L,x");
  emit("        sta ZP_F1_L");
  emit("        lda PHON_F1_H,x");
  emit("        sta ZP_F1_H");
  emit("        lda PHON_F2_L,x");
  emit("        sta ZP_F2_L");
  emit("        lda PHON_F2_H,x");
  emit("        sta ZP_F2_H");
  emit("");
  emit("        ; Set Formant 1 (Channel A)");
  emit("        ldy #0              ; R0: Tone A Period Fine");
  emit("        lda ZP_F1_L");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #1              ; R1: Tone A Period Coarse");
  emit("        lda ZP_F1_H");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Set Formant 2 (Channel B)");
  emit("        ldy #2              ; R2: Tone B Period Fine");
  emit("        lda ZP_F2_L");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #3              ; R3: Tone B Period Coarse");
  emit("        lda ZP_F2_H");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Set Voice Bar (Channel C: F0 = 125 Hz -> period 786 = $0312)");
  emit("        ldy #4              ; R4: Tone C Period Fine");
  emit("        lda #$12");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #5              ; R5: Tone C Period Coarse");
  emit("        lda #$03");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Set Noise Period (R6)");
  emit("        ldy #6");
  emit("        lda PHON_NOISE,x");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Set Channel Amplitudes");
  emit("        ; Channel A amplitude (R8)");
  emit("        ldy #8");
  emit("        lda PHON_MODE,x");
  emit("        and #1              ; Tone A/B enabled?");
  emit("        beq CH_A_NOISE_CHECK");
  emit("        lda PHON_VOL,x");
  emit("        bra WRITE_VOL_A");
  emit("CH_A_NOISE_CHECK:");
  emit("        lda PHON_MODE,x");
  emit("        and #4              ; Noise enabled?");
  emit("        beq CH_A_OFF");
  emit("        lda PHON_VOL,x      ; Noise volume routed through Channel A");
  emit("        bra WRITE_VOL_A");
  emit("CH_A_OFF:");
  emit("        lda #0");
  emit("WRITE_VOL_A:");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Channel B amplitude (R9)");
  emit("        ldy #9");
  emit("        lda PHON_MODE,x");
  emit("        and #1              ; Tone A/B enabled?");
  emit("        beq CH_B_OFF");
  emit("        lda PHON_VOL,x");
  emit("        bra WRITE_VOL_B");
  emit("CH_B_OFF:");
  emit("        lda #0");
  emit("WRITE_VOL_B:");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Channel C amplitude (R10: Voice bar)");
  emit("        ldy #10");
  emit("        lda PHON_MODE,x");
  emit("        and #2              ; Tone C voice bar enabled?");
  emit("        beq CH_C_OFF");
  emit("        lda #9              ; Voice bar volume 9");
  emit("        bra WRITE_VOL_C");
  emit("CH_C_OFF:");
  emit("        lda #0");
  emit("WRITE_VOL_C:");
  emit("        jsr AY_WRITE_BOTH");
  emit("");
  emit("        ; Configure Hardware Envelope (R11, R12, R13)");
  emit("        lda PHON_MODE,x");
  emit("        and #8              ; Envelope modulation?");
  emit("        beq SKIP_ENVELOPE");
  emit("        ldy #11             ; R11: Envelope Fine (49 = $31 for ~125 Hz)");
  emit("        lda #$31");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #12             ; R12: Envelope Coarse");
  emit("        lda #0");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #13             ; R13: Shape 8 (repeating sawtooth)");
  emit("        lda #8");
  emit("        jsr AY_WRITE_BOTH");
  emit("SKIP_ENVELOPE:");
  emit("");
  emit("        ; Configure Mixer (R7)");
  emit("        ; Bits: 0=Tone A, 1=Tone B, 2=Tone C, 3=Noise A, 4=Noise B, 5=Noise C (0=enable, 1=disable)");
  emit("        lda #$3F            ; Default: disable all tones and noise");
  emit("        sta ZP_AY_BASE      ; Use ZP_AY_BASE as mixer mask accumulator");
  emit("        lda PHON_MODE,x");
  emit("        and #1              ; Tone A/B enabled?");
  emit("        beq MIXER_NO_TONE_AB");
  emit("        lda ZP_AY_BASE");
  emit("        and #$FC            ; Enable Tone A and B (clear bits 0 and 1)");
  emit("        sta ZP_AY_BASE");
  emit("MIXER_NO_TONE_AB:");
  emit("        lda PHON_MODE,x");
  emit("        and #2              ; Tone C enabled?");
  emit("        beq MIXER_NO_TONE_C");
  emit("        lda ZP_AY_BASE");
  emit("        and #$FB            ; Clear bit 2 (enable Tone C)");
  emit("        sta ZP_AY_BASE");
  emit("MIXER_NO_TONE_C:");
  emit("        lda PHON_MODE,x");
  emit("        and #4              ; Noise enabled?");
  emit("        beq MIXER_DONE");
  emit("        lda ZP_AY_BASE");
  emit("        and #$F7            ; Clear bit 3 (enable Noise A)");
  emit("        sta ZP_AY_BASE");
  emit("MIXER_DONE:");
  emit("        lda ZP_AY_BASE");
  emit("        ora #$C0            ; Keep I/O port bits set");
  emit("        ldy #7              ; R7: Mixer control");
  emit("        jsr AY_WRITE_BOTH");
  emit("        rts");
  emit("");
  emit("; Program glide target for diphthong phoneme X");
  emit("PROGRAM_GLIDE_TARGET:");
  emit("        lda PHON_F1B_L,x");
  emit("        sta ZP_F1_L");
  emit("        lda PHON_F1B_H,x");
  emit("        sta ZP_F1_H");
  emit("        lda PHON_F2B_L,x");
  emit("        sta ZP_F2_L");
  emit("        lda PHON_F2B_H,x");
  emit("        sta ZP_F2_H");
  emit("        ldy #0");
  emit("        lda ZP_F1_L");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #1");
  emit("        lda ZP_F1_H");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #2");
  emit("        lda ZP_F2_L");
  emit("        jsr AY_WRITE_BOTH");
  emit("        ldy #3");
  emit("        lda ZP_F2_H");
  emit("        jsr AY_WRITE_BOTH");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; AY-3-8910 HARDWARE DRIVERS (SLOT 4 MOCKINGBOARD)");
  emit("; ==========================================================================");
  emit("; Initialize VIA/AY chip at offset X ($00 for Left, $80 for Right)");
  emit("AY_INIT_CHIP:");
  emit("        lda #$FF");
  emit("        sta MB_LEFT+VIA_DDRA,x   ; Port A all outputs (AY data bus)");
  emit("        lda #7");
  emit("        sta MB_LEFT+VIA_DDRB,x   ; Port B bits 0,1,2 output (BC1, BDIR, /RESET)");
  emit("        lda #0");
  emit("        sta MB_LEFT+VIA_ORB,x    ; /RESET low (reset chip)");
  emit("        lda #4");
  emit("        sta MB_LEFT+VIA_ORB,x    ; /RESET high, inactive (BC1=0, BDIR=0)");
  emit("        rts");
  emit("");
  emit("; Write AY register Y with data A on chip offset X");
  emit("; Preserve A, X, Y");
  emit("AY_WRITE_REG:");
  emit("        sta ZP_AY_VAL");
  emit("        phx");
  emit("        phy");
  emit("        ; Step 1: Latch register address");
  emit("        tya");
  emit("        sta MB_LEFT+VIA_ORA,x");
  emit("        lda #7                  ; BC1=1, BDIR=1 (Latch Address)");
  emit("        sta MB_LEFT+VIA_ORB,x");
  emit("        lda #4                  ; Inactive");
  emit("        sta MB_LEFT+VIA_ORB,x");
  emit("        ; Step 2: Write data to latched register");
  emit("        lda ZP_AY_VAL");
  emit("        sta MB_LEFT+VIA_ORA,x");
  emit("        lda #6                  ; BC1=0, BDIR=1 (Write to PSG)");
  emit("        sta MB_LEFT+VIA_ORB,x");
  emit("        lda #4                  ; Inactive");
  emit("        sta MB_LEFT+VIA_ORB,x");
  emit("        ply");
  emit("        plx");
  emit("        lda ZP_AY_VAL");
  emit("        rts");
  emit("");
  emit("; Write register Y with data A to BOTH Left and Right AY chips");
  emit("; Preserve X, Y");
  emit("AY_WRITE_BOTH:");
  emit("        sta ZP_AY_VAL");
  emit("        phx");
  emit("        ldx #0                  ; Left AY");
  emit("        jsr AY_WRITE_REG");
  emit("        lda ZP_AY_VAL");
  emit("        ldx #$80                ; Right AY");
  emit("        jsr AY_WRITE_REG");
  emit("        plx");
  emit("        rts");
  emit("");
  emit("; Mute all channels on both AY chips");
  emit("AY_MUTE_ALL:");
  emit("        ldy #8");
  emit("        lda #0");
  emit("        jsr AY_WRITE_BOTH       ; Volume A = 0");
  emit("        ldy #9");
  emit("        lda #0");
  emit("        jsr AY_WRITE_BOTH       ; Volume B = 0");
  emit("        ldy #10");
  emit("        lda #0");
  emit("        jsr AY_WRITE_BOTH       ; Volume C = 0");
  emit("        ldy #7");
  emit("        lda #$FF");
  emit("        jsr AY_WRITE_BOTH       ; Disable all tones & noise");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; FRAME DELAY & ESCAPE POLL");
  emit("; Waits ~15 ms (approx 23,600 cycles). Polls keyboard for Escape every 0.5 ms.");
  emit("; Sets ZP_ESCAPE_HIT=1 and clears strobe if Escape is pressed.");
  emit("; ==========================================================================");
  emit("DELAY_FRAME:");
  emit("        ldx #30                 ; 30 intervals of ~787 cycles = ~23,610 cycles (~15 ms)");
  emit("DELAY_INTERVAL_LOOP:");
  emit("        ; Poll keyboard");
  emit("        lda KBD");
  emit("        bpl DELAY_NO_KEY        ; Bit 7 clear: no key pressed");
  emit("        cmp #$9B                ; Escape ($1B with bit 7 set = $9B)");
  emit("        bne DELAY_CLEAR_OTHER_KEY");
  emit("        ; Escape pressed! Cancel immediately");
  emit("        bit KBD_STROBE");
  emit("        lda #1");
  emit("        sta ZP_ESCAPE_HIT");
  emit("        rts");
  emit("DELAY_CLEAR_OTHER_KEY:");
  emit("        bit KBD_STROBE");
  emit("DELAY_NO_KEY:");
  emit("        ; Inner delay: ~760 cycles");
  emit("        ldy #150");
  emit("DELAY_INNER:");
  emit("        dey");
  emit("        bne DELAY_INNER");
  emit("        dex");
  emit("        bne DELAY_INTERVAL_LOOP");
  emit("        rts");
  emit("");
  emit("; ==========================================================================");
  emit("; INTERACTIVE TEXT-MODE UI");
  emit("; User interface for standalone interactive typing and speech.");
  emit("; ==========================================================================");
  emit("UI:");
  emit("        ; Switch to text mode page 1");
  emit("        bit TEXT_SW");
  emit("        bit FULL_SW");
  emit("        bit PAGE1_SW");
  emit("        jsr ROM_HOME");
  emit("        jsr TTS_INIT");
  emit("");
  emit("        ; Print Banner");
  emit("        ldx #0");
  emit("PRINT_BANNER_LOOP:");
  emit("        lda MSG_BANNER,x");
  emit("        beq BANNER_LINE1_DONE");
  emit("        ora #$80");
  emit("        jsr ROM_COUT");
  emit("        inx");
  emit("        bne PRINT_BANNER_LOOP");
  emit("BANNER_LINE1_DONE:");
  emit("        jsr ROM_CROUT");
  emit("        ldx #0");
  emit("PRINT_HELP_LOOP:");
  emit("        lda MSG_HELP,x");
  emit("        beq BANNER_DONE");
  emit("        ora #$80");
  emit("        jsr ROM_COUT");
  emit("        inx");
  emit("        bne PRINT_HELP_LOOP");
  emit("BANNER_DONE:");
  emit("");
  emit("UI_PROMPT_LOOP:");
  emit("        jsr ROM_CROUT");
  emit("        lda #$BE                ; '>' | $80");
  emit("        jsr ROM_COUT");
  emit("        lda #$A0                ; ' ' | $80");
  emit("        jsr ROM_COUT");
  emit("");
  emit("        ; Clear TTS_INPUT buffer");
  emit("        ldx #0");
  emit("CLEAR_BUF_LOOP:");
  emit("        stz TTS_INPUT,x");
  emit("        inx");
  emit("        cpx #122");
  emit("        bcc CLEAR_BUF_LOOP");
  emit("");
  emit("        ldx #0                  ; Current input length");
  emit("");
  emit("UI_KEY_LOOP:");
  emit("        jsr ROM_RDKEY");
  emit("        and #$7F                ; Convert from high-bit ASCII");
  emit("");
  emit("        ; Check Escape ($1B)");
  emit("        cmp #$1B");
  emit("        bne NOT_ESC_KEY");
  emit("        ; Escape at input: exit with BRK");
  emit("        jsr AY_MUTE_ALL");
  emit("        jsr ROM_CROUT");
  emit("        brk");
  emit("");
  emit("NOT_ESC_KEY:");
  emit("        ; Check Enter ($0D)");
  emit("        cmp #$0D");
  emit("        beq UI_ENTER_PRESSED");
  emit("");
  emit("        ; Check Backspace / Delete ($08 or $7F)");
  emit("        cmp #$08");
  emit("        beq UI_BACKSPACE");
  emit("        cmp #$7F");
  emit("        beq UI_BACKSPACE");
  emit("");
  emit("        ; Printable character check");
  emit("        cmp #' '");
  emit("        bcc UI_KEY_LOOP         ; Ignore control characters");
  emit("        cmp #$7F");
  emit("        bcs UI_KEY_LOOP");
  emit("");
  emit("        ; Buffer limit check (max 120 chars)");
  emit("        cpx #120");
  emit("        bcs UI_BEEP_FULL");
  emit("");
  emit("        ; Store character in buffer and echo");
  emit("        sta TTS_INPUT,x");
  emit("        inx");
  emit("        ora #$80");
  emit("        jsr ROM_COUT");
  emit("        jmp UI_KEY_LOOP");
  emit("");
  emit("UI_BEEP_FULL:");
  emit("        jsr ROM_BELL");
  emit("        jmp UI_KEY_LOOP");
  emit("");
  emit("UI_BACKSPACE:");
  emit("        cpx #0");
  emit("        beq UI_KEY_LOOP");
  emit("        dex");
  emit("        stz TTS_INPUT,x");
  emit("        ; Erase character on screen: Backspace, Space, Backspace");
  emit("        lda #$88                ; Backspace");
  emit("        jsr ROM_COUT");
  emit("        lda #$A0                ; ' ' | $80");
  emit("        jsr ROM_COUT");
  emit("        lda #$88");
  emit("        jsr ROM_COUT");
  emit("        jmp UI_KEY_LOOP");
  emit("");
  emit("UI_ENTER_PRESSED:");
  emit("        ; NUL-terminate");
  emit("        lda #0");
  emit("        sta TTS_INPUT,x");
  emit("        jsr ROM_CROUT");
  emit("");
  emit("        ; Call TTS_SPEAK");
  emit("        lda #<TTS_INPUT");
  emit("        ldx #>TTS_INPUT");
  emit("        jsr TTS_SPEAK");
  emit("");
  emit("        cmp #1");
  emit("        bne NOT_UI_CANCELLED");
  emit("        ; Print [CANCELLED]");
  emit("        ldx #0");
  emit("PRINT_CANCEL_LOOP:");
  emit("        lda MSG_CANCEL,x");
  emit("        beq NOT_UI_CANCELLED");
  emit("        ora #$80");
  emit("        jsr ROM_COUT");
  emit("        inx");
  emit("        bne PRINT_CANCEL_LOOP");
  emit("");
  emit("NOT_UI_CANCELLED:");
  emit("        jmp UI_PROMPT_LOOP");
  emit("");
  emit("; UI Messages");
  emit("MSG_BANNER:");
  emit("        .asciiz \"3RIC TALKS V1 - GEMINI 3.8 FLASH TTS\"");
  emit("MSG_HELP:");
  emit("        .asciiz \"TYPE SENTENCE + ENTER. ESC CANCELS.\"");
  emit("MSG_CANCEL:");
  emit("        .asciiz \" [CANCELLED]\"");
  emit("");
  emit("; ==========================================================================");
  emit("; PHONEME ACOUSTIC TABLES");
  emit("; ==========================================================================");
  emit("; Duration in ~15 ms frames");
  emit("PHON_DUR:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => p.dur).join(", ")}`);
  }
  emit("");
  emit("; Synthesis mode flags");
  emit("PHON_MODE:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${p.mode.toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Formant 1 period low byte");
  emit("PHON_F1_L:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${(calcPeriod(p.f1) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Formant 1 period high byte");
  emit("PHON_F1_H:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${((calcPeriod(p.f1) >> 8) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Formant 2 period low byte");
  emit("PHON_F2_L:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${(calcPeriod(p.f2) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Formant 2 period high byte");
  emit("PHON_F2_H:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${((calcPeriod(p.f2) >> 8) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Noise period (0-31)");
  emit("PHON_NOISE:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${p.noise.toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Volume / Amplitude setting");
  emit("PHON_VOL:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${p.vol.toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Diphthong glide target F1 low byte");
  emit("PHON_F1B_L:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${(calcPeriod(p.f1b || p.f1) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Diphthong glide target F1 high byte");
  emit("PHON_F1B_H:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${((calcPeriod(p.f1b || p.f1) >> 8) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Diphthong glide target F2 low byte");
  emit("PHON_F2B_L:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${(calcPeriod(p.f2b || p.f2) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; Diphthong glide target F2 high byte");
  emit("PHON_F2B_H:");
  for (let i = 0; i < PHONEME_LIST.length; i += 8) {
    const chunk = PHONEME_LIST.slice(i, i + 8);
    emit(`        .byte ${chunk.map(p => `$${((calcPeriod(p.f2b || p.f2) >> 8) & 0xFF).toString(16).padStart(2, "0").toUpperCase()}`).join(", ")}`);
  }
  emit("");
  emit("; ==========================================================================");
  emit("; PRONUNCIATION EXCEPTION DICTIONARY");
  emit("; Format: .byte word_len, \"WORD\", phon_count, P_PHON1, P_PHON2, ...");
  emit("; Terminated by .byte 0");
  emit("; ==========================================================================");
  emit("DICTIONARY_DATA:");
  for (const [word, phonemes] of Object.entries(EXCEPTIONS)) {
    const pNames = phonemes.map(p => `P_${p}`).join(", ");
    emit(`        .byte ${word.length}, "${word}", ${phonemes.length}, ${pNames}`);
  }
  emit("        .byte 0             ; End of dictionary");
  emit("");
  emit("; ==========================================================================");
  emit("; APPLICATION WORKSPACE & INPUT BUFFERS");
  emit("; ==========================================================================");
  emit("PHONEME_BUF:    .res 256    ; Buffer of phoneme IDs for current sentence");
  emit("WORD_BUF:       .res 32     ; Normalization buffer for current word");
  emit("");
  emit("; TTS_INPUT: Mandatory 122 consecutive bytes in always-mapped RAM ($0800..$8FFF)");
  emit("TTS_INPUT:      .res 122");
  emit("");

  return lines.join("\n");
}

const source = generateSource();
const outPath = path.join(HERE, "tts.s");
fs.writeFileSync(outPath, source);
console.log(`Successfully generated ${outPath} (${source.length} bytes, ${source.split("\n").length} lines).`);
