<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <BaseOutputPath Condition="'$(BaseOutputPath)' == ''">bin\</BaseOutputPath>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">obj\</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)' == ''">$(BaseOutputPath)$(Platform)\$(Configuration)\</OutputPath>
    <IntermediateOutputPath Condition="'$(IntermediateOutputPath)' == ''">$(BaseIntermediateOutputPath)$(Platform)\$(Configuration)\</IntermediateOutputPath>
    <DefaultPlatformToolset Condition="'$(DefaultPlatformToolset)' == ''">v145</DefaultPlatformToolset>
    <AppxPackageDir Condition="'$(AppxPackageDir)' == ''">$(OutputPath)AppPackages\</AppxPackageDir>
  </PropertyGroup>
</Project>
